{{- if .Values.logging.enabled }}
{{- if .Values.odoo.enabled }}
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: {{ include "socialRegistry.fullname" . }}-odoo
spec:
  filters:
  - parser:
      {{- include "common.tplvalues.render" (dict "value" .Values.logging.parser "context" $) | nindent 4 }}
  {{- if .Values.logging.extraFilters }}
  {{- include "common.tplvalues.render" (dict "value" .Values.logging.extraFilters "context" $) | nindent 2 }}
  {{- end }}
  localOutputRefs:
  - {{ .Values.logging.outputRef }}
  {{- if .Values.logging.extraLocalOutputRefs }}
  {{- include "common.tplvalues.render" (dict "value" .Values.logging.extraLocalOutputRefs "context" $) | nindent 2 }}
  {{- end }}
  {{- if .Values.logging.globalOutputRefs }}
  globalOutputRefs: {{- include "common.tplvalues.render" (dict "value" .Values.logging.globalOutputRefs "context" $) | nindent 2 }}
  {{- end }}
  match:
  - select:
      labels:
        {{- include "common.labels.matchLabels" (dict "customLabels" .Values.odoo.podLabels "context" $.Subcharts.odoo) | nindent 8 }}
{{- end }}
{{- end }}
