{{- if .Values.superset.enabled  }}
{{- if .Values.superset.istio.enabled  }}
{{- if .Values.superset.istio.gateway.enabled  }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Release.Name }}-superset
  labels:
    {{- include "socialRegistry.labels" . | nindent 4 }}
spec:
  selector:
    {{ toYaml .Values.superset.istio.gateway.ingressController | nindent 4 }}
  servers:
  {{- if .Values.superset.istio.gateway.httpEnabled }}
  - port:
      name: http2
      number: 8080
      protocol: HTTP2
    hosts:
      - {{ default .Values.global.supersetHostname .Values.superset.istio.gateway.host | quote }}
    {{- if .Values.superset.istio.gateway.httpTlsRedirect }}
    tls:
      httpsRedirect: true
    {{- end }}
  {{- end }}
  {{- if .Values.superset.istio.gateway.httpsEnabled }}
  - port:
      name: https
      number: 8443
      protocol: HTTPS
    hosts:
      - {{ default .Values.global.supersetHostname .Values.superset.istio.gateway.host | quote }}
    tls:
      {{ toYaml (omit .Values.superset.istio.gateway.tls "enabled") | nindent 6 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
