{{- if .Values.istio.enabled }}
{{- if .Values.istio.virtualservice.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "socialRegistry.fullname" . }}
  labels:
    {{- include "socialRegistry.labels" . | nindent 4 }}
spec:
  hosts:
  - {{ default .Values.global.socialRegistryHostname .Values.istio.virtualservice.host | quote }}
  gateways:
  - {{ default (include "socialRegistry.fullname" .) .Values.istio.virtualservice.gateway }}
  http:
  - match:
    - uri:
        exact: /
    redirect:
      uri: /web
  - headers:
      request:
        set:
          x-forwarded-host: {{ default .Values.global.socialRegistryHostname .Values.istio.virtualservice.host | quote }}
          x-forwarded-proto: https
    route:
    - destination:
        host: {{ tpl .Values.istio.virtualservice.destination $ }}
        port:
          number: {{ tpl .Values.istio.virtualservice.destinationPort $ }}
{{- end }}
{{- end }}
