{{- if .Values.minio.enabled }}
{{- if .Values.minio.istio.enabled }}
{{- if .Values.minio.istio.virtualservice.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "common.names.fullname" .Subcharts.minio }}
  labels: {{ include "common.labels.standard" (dict "customLabels" .Values.minio.commonLabels "context" .Subcharts.minio) | nindent 4 }}
  {{- if .Values.minio.commonAnnotations }}
  annotations: {{ include "common.tplvalues.render" (dict "value" .Values.minio.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  hosts:
  - {{ default .Values.minio.hostname .Values.minio.istio.virtualservice.host | quote }}
  gateways:
  - {{ default (include "common.names.fullname" .Subcharts.minio) .Values.minio.istio.virtualservice.gateway }}
  http:
  - headers:
      request:
        set:
          x-forwarded-host: {{ default .Values.minio.hostname .Values.minio.istio.virtualservice.host | quote }}
          x-forwarded-proto: https
    route:
    - destination:
        host: {{ tpl .Values.minio.istio.virtualservice.destination $ }}
        port:
          number: {{ tpl .Values.minio.istio.virtualservice.destinationPort $ }}
{{- end }}
{{- end }}
{{- end }}
