apiVersion: v2
name: openg2p-social-registry
description: A Helm chart for OpenG2P Social Registry
type: application
version: 2.0.8
dependencies:
- name: odoo
  version: 26.2.9
  repository: https://openg2p.github.io/openg2p-helm
  condition: odoo.enabled
- name: mail
  version: 1.2.1
  repository: https://openg2p.github.io/openg2p-helm
  condition: mail.enabled
- name: minio
  version: 12.12.2
  repository: https://openg2p.github.io/openg2p-helm
  condition: minio.enabled
- name: odk-central
  version: v2025.2.1
  repository: https://openg2p.github.io/openg2p-helm
  condition: odk-central.enabled
- name: redis
  alias: odk-central-enketo-redis-main
  version: 19.6.4
  repository: https://openg2p.github.io/openg2p-helm
  condition: odk-central-enketo-redis-main.enabled
- name: redis
  alias: odk-central-enketo-redis-cache
  version: 19.6.4
  repository: https://openg2p.github.io/openg2p-helm
  condition: odk-central-enketo-redis-cache.enabled
- name: opensearch
  version: 1.2.0
  repository: https://openg2p.github.io/openg2p-helm
  condition: opensearch.enabled
- name: kafka
  repository: https://openg2p.github.io/openg2p-helm
  version: 29.3.14
  condition: kafka.enabled
- name: artifactory
  version: 12.0.3
  repository: https://openg2p.github.io/openg2p-helm
  condition: artifactory.enabled
- name: keymanager
  version: 12.0.3
  repository: https://openg2p.github.io/openg2p-helm
  condition: keymanager.enabled
- name: softhsm
  repository: https://mosip.github.io/mosip-helm
  version: 12.0.1
  condition: softhsm.enabled
- name: idgenerator
  version: 12.0.3
  repository: https://openg2p.github.io/openg2p-helm
  condition: idgenerator.enabled
- name: reporting
  version: 1.3.0
  repository: https://openg2p.github.io/openg2p-helm
  condition: reporting.enabled
- name: reporting-init
  version: 1.3.0
  repository: https://openg2p.github.io/openg2p-helm
  condition: reporting-init.enabled
- name: redis
  alias: bgTasksRedis
  version: 19.6.4
  repository: https://openg2p.github.io/openg2p-helm
  condition: openg2p-registry-bg-tasks.enabled
- name: openg2p-registry-bg-tasks
  version: 1.1.2
  repository: https://openg2p.github.io/openg2p-helm
  condition: openg2p-registry-bg-tasks.enabled
- name: superset
  version: 0.12.11
  repository: https://apache.github.io/superset
  condition: superset.enabled
- name: redis
  alias: supersetRedis
  version: 19.6.4
  repository: https://openg2p.github.io/openg2p-helm
  condition: superset.enabled
- name: esignet
  version: 1.4.3
  repository: https://openg2p.github.io/openg2p-helm
  condition: esignet.enabled
- name: redis
  alias: esignetRedis
  version: 19.6.4
  repository: https://openg2p.github.io/openg2p-helm
  condition: esignet.enabled
- name: mock-identity-system
  version: 0.9.5
  repository: https://openg2p.github.io/openg2p-helm
  condition: mock-identity-system.enabled
icon: https://openg2p.github.io/openg2p-helm/openg2p-logo.png
annotations:
  catalog.cattle.io/display-name: "OpenG2P Social Registry"
  openg2p.org/add-to-rancher: ""
