global:
  socialRegistryHostname: socialregistry.openg2p.sandbox.net
  odkHostname: odk.openg2p.sandbox.net
  opensearchHostname: opensearch.openg2p.sandbox.net
  minioHostname: minio.openg2p.sandbox.net
  supersetHostname: superset.openg2p.sandbox.net
  keymanagerHostname: keymanager.openg2p.sandbox.net
  esignetHostname: esignet.openg2p.sandbox.net
  mailname: openg2p.sandbox.net
  sysAdminEmail: admin@openg2p.sandbox.net

  socialRegistryAuthClientId: 'openg2p-sr'
  socialRegistryAuthClientSecret: ''

  socialRegistryMailInstallationName: '{{ .Release.Name }}-mail'
  socialRegistryOpensearchInstallationName: '{{ .Release.Name }}-opensearch'

  keycloakBaseUrl: https://keycloak.openg2p.sandbox.net
  keycloakIssuerUrl: '{{ tpl .Values.global.keycloakBaseUrl $ }}/realms/master'

  socialRegistryKeymanagerInstallationName: '{{ .Release.Name }}-keymanager'
  socialRegistryKeymanagerAuthClientId: '{{ tpl .Values.global.socialRegistryAuthClientId $ }}'
  socialRegistryKeymanagerAuthClientSecret: '{{ tpl .Values.global.socialRegistryAuthClientSecret $ }}'

odoo:
  enabled: true
  image:
    repository: openg2p/openg2p-social-registry-odoo-package
    tag: "17.0-develop-social-registry"
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 80

  # TODO: Remove this and use global.sysAdminEmail
  odooEmail: admin@openg2p.org

  postgresql:
    enabled: true
    primary:
      extendedConfiguration: |-
        wal_level = logical
        max_wal_senders = 20
        max_replication_slots = 10
    istio:
      enabled: false
      virtualservice:
        enabled: true
        host: "*"
        gateway: ""
        matchPort: 5432
        destination: '{{ .Release.Name }}-postgresql'
        destinationPort: "5432"
      gateway:
        enabled: true
        port: 5432
        host: "*"
        ingressController:
          istio: ingressgateway
        tls:
          enabled: false
          mode: SIMPLE
          credentialName: ""

  livenessProbe:
    enabled: false

  # TODO: Template the following variables from helm values, instead of hardcoding
  extraEnvVars:
  - name: ODOO_SKIP_MODULES_UPDATE
    value: "yes"
  - name: LIMIT_TIME_REAL
    value: "5000"
  - name: LIST_DB
    value: "False"
  - name: SERVER_WIDE_MODULES
    value: web,queue_job
  # not using bitnami smtpHost and smtpPort variables, because they need user and pass as well.
  - name: OPENG2P_SMTP_HOST
    value: '{{ tpl .Values.global.socialRegistryMailInstallationName $ }}'
  - name: OPENG2P_SMTP_PORT_NUMBER
    value: "25"
  - name: LOG_HANDLER
    value: "[':INFO']"
  - name: LOG_DB
    value: "False"
  - name: KEYMANAGER_API_BASE_URL
    value: '{{ tpl .Values.global.socialRegistryKeymanagerInstallationName $ }}'
  - name: KEYMANAGER_AUTH_URL
    value: '{{ tpl .Values.global.keycloakIssuerUrl $ }}/protocol/openid-connect/token'
  - name: KEYMANAGER_AUTH_CLIENT_ID
    value: '{{ tpl .Values.global.socialRegistryKeymanagerAuthClientId $ }}'
  - name: KEYMANAGER_AUTH_CLIENT_SECRET
    value: '{{ tpl .Values.global.socialRegistryKeymanagerAuthClientSecret $ }}'

esignet:
  enabled: false
  captchaEnabled: false
  envVars:
    esignet_captcha_site_key: ''
    esignet_captcha_secret_key: ''
  mock-identity-system:
    enabled: true
    springConfig:
      names: application,mock-identity-system
      profile: default
      gitRepo:
        enabled: true
        repoUrl: https://github.com/openg2p/mosip-config
        branch: master
      rawConfig: ""
  springConfig:
    names: application,esignet
    profile: default
    gitRepo:
      enabled: true
      repoUrl: https://github.com/openg2p/mosip-config
      branch: master
    rawConfig: ""

keymanager:
  enabled: true
  springConfig:
    names: application,kernel
    profile: default
    gitRepo:
      enabled: true
      repoUrl: https://github.com/openg2p/mosip-config
      branch: master
    rawConfig: ""
  envVars:
    auth_server_admin_allowed_audience: 'openg2p-sr,openg2p-sr-{{ .Release.Namespace }},openg2p-pbms,openg2p-pbms-{{ .Release.Namespace }},openg2p-spar-{{ .Release.Namespace }}'

mail:
  enabled: true

odk-central:
  enabled: false
  odk-central-mail:
    enabled: false
  odk-central-backend:
    envVars:
      EMAIL_HOST: '{{ tpl .Values.global.socialRegistryMailInstallationName $ }}'
      OIDC_ISSUER_URL: '{{ tpl .Values.global.keycloakIssuerUrl $ }}'
      OIDC_CLIENT_ID: ""
      OIDC_CLIENT_SECRET: ""

minio:
  enabled: true
  persistence:
    enabled: true
    size: 16Gi

  oidcWellKnownConfigUrl: '{{ tpl .Values.global.keycloakIssuerUrl $ }}/.well-known/openid-configuration'
  oidcClientId: openg2p-sr-minio
  oidcClientSecret: ''

  extraEnvVars:
  - name: MINIO_IDENTITY_OPENID_CONFIG_URL
    value: '{{ tpl .Values.oidcWellKnownConfigUrl $ }}'
  - name: MINIO_IDENTITY_OPENID_CLIENT_ID
    value: '{{ tpl .Values.oidcClientId $ }}'
  - name: MINIO_IDENTITY_OPENID_CLIENT_SECRET
    value: '{{ tpl .Values.oidcClientSecret $ }}'
  - name: MINIO_IDENTITY_OPENID_DISPLAY_NAME
    value: Keycloak
  - name: MINIO_IDENTITY_OPENID_CLAIM_NAME
    value: client_roles
  - name: MINIO_IDENTITY_OPENID_SCOPES
    value: openid,profile,email
  - name: MINIO_IDENTITY_OPENID_REDIRECT_URI_DYNAMIC
    value: "on"
  - name: MINIO_IDENTITY_OPENID_CLAIM_USERINFO
    value: "on"

  istio:
    enabled: true
    virtualservice:
      enabled: true
      host: ""
      gateway: "internal"
      destination: '{{ .Release.Name }}-minio'
      destinationPort: "9001"
    gateway:
      enabled: false
      host: ""
      ingressController:
        istio: ingressgateway
      httpTlsRedirect: true
      httpEnabled: true
      httpsEnabled: false
      tls:
        mode: SIMPLE
        credentialName: ""

opensearch:
  enabled: false

  oidcWellKnownConfigUrl: '{{ tpl .Values.global.keycloakIssuerUrl $ }}/.well-known/openid-configuration'
  oidcClientId: openg2p-sr-opensearch
  oidcClientSecret: ''

  master:
    replicaCount: 1
    persistence:
      size: 8Gi
    heapSize: 256m
    masterOnly: false

  data:
    replicaCount: 0
    # persistence:
    #   size: 8Gi

  coordinating:
    replicaCount: 0

  ingest:
    replicaCount: 0

  extraVolumes:
  - name: security-config
    configMap:
      name: '{{ .Release.Name }}-opensearch-custom-config'

  extraVolumeMounts:
  - name: security-config
    mountPath: /opt/bitnami/opensearch/config.default/opensearch-security/config.yml
    subPath: opensearch-security-config.yml

  security:
    enabled: true
    tls:
      restEncryption: true
    extraConfig: |-
      _meta:
        type: "config"
        config_version: 2

      config:
        dynamic:
          http:
            anonymous_auth_enabled: false
            xff:
              enabled: false
          authc:
            basic_internal_auth_domain:
              http_enabled: true
              transport_enabled: true
              order: 0
              description: "Authenticate via HTTP Basic against internal users database"
              http_authenticator:
                type: basic
                challenge: false
              authentication_backend:
                type: internal
            openid_auth_domain:
              http_enabled: true
              transport_enabled: true
              order: 1
              description: "Authenticate via Keycloak OIDC"
              http_authenticator:
                type: openid
                challenge: false
                config:
                  subject_key: preferred_username
                  roles_key: groups
                  openid_connect_url: '{{ tpl .Values.opensearch.oidcWellKnownConfigUrl $ }}'
              authentication_backend:
                type: noop
            kerberos_auth_domain:
              http_enabled: false
              transport_enabled: false
            proxy_auth_domain:
              http_enabled: false
              transport_enabled: false
            jwt_auth_domain:
              http_enabled: false
              transport_enabled: false
            clientcert_auth_domain:
              http_enabled: false
              transport_enabled: false
            ldap:
              http_enabled: false
              transport_enabled: false
          authz: {}

  dashboards:
    enabled: true
    replicaCount: 1

    extraVolumes:
    - name: dashboards-config
      configMap:
        name: '{{ .Release.Name }}-opensearch-custom-config'

    extraVolumeMounts:
    - name: dashboards-config
      mountPath: /opt/bitnami/opensearch-dashboards/config.default/opensearch_dashboards.yml
      subPath: opensearch_dashboards.yml

    extraConfig: |-
      path:
        data: /bitnami/opensearch-dashboards/data
      opensearch:
        requestHeadersAllowlist:
          - authorization
          - securitytenant
        ssl:
          verificationMode: none
      opensearch_security:
        auth:
          type:
          # - basicauth # Enable this to allow password based auth also
          - openid
          multiple_auth_enabled: true
        openid:
          connect_url: '{{ tpl .Values.opensearch.oidcWellKnownConfigUrl $ }}'
          client_id: '{{ tpl .Values.opensearch.oidcClientId $ }}'
          client_secret: '{{ tpl .Values.opensearch.oidcClientSecret $ }}'
          base_redirect_url: 'https://{{ .Values.global.opensearchHostname }}'
          logout_url: ""
        ui:
          openid:
            login:
              buttonname: "Log in with Keycloak"
        multitenancy:
          enabled: false # Enable this if multi tenancy is needed.
          tenants:
            preferred:
            - Global
            - Private
        readonly_mode:
          roles:
          - kibana_read_only

  loggingOutput:
    enabled: false
    type: opensearch
    scheme: https
    host: '{{ printf "%s-opensearch.%s" (.Release.Name) (.Release.Namespace) }}'
    port: "9200"
    user: logstash
    passwordFrom:
      secretKeyRef:
        key: logstash-password
        name: '{{ .Release.Name }}-opensearch'
    extraConfig:
      ssl_verify: false
      logstash_format: true
      suppress_type_name: true
      buffer:
        flush_interval: 10s
        flush_mode: interval
  istio:
    enabled: true
    virtualservice:
      enabled: true
      host: ""
      gateway: "internal"
      destination: '{{ .Release.Name }}-opensearch-dashboards'
      destinationPort: "5601"
    gateway:
      enabled: false
      host: ""
      ingressController:
        istio: ingressgateway
      httpTlsRedirect: true
      httpEnabled: true
      httpsEnabled: false
      tls:
        mode: SIMPLE
        credentialName: ""

# TODO: Doing this since postgres and redis charts inside superset are old.
supersetPostgresql:
  nameOverride: superset-postgresql
  auth:
    username: superset
    password: superset
    database: superset
  primary:
    extendedConfiguration: |-
      wal_level = logical
      max_wal_senders = 20
      max_replication_slots = 10
supersetRedis:
  nameOverride: superset-redis
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: false

superset:
  enabled: false

  oidcIssuerUrl: '{{ tpl .Values.global.keycloakIssuerUrl $ }}'
  oidcClientId: openg2p-sr-superset
  oidcClientSecret: ''

  supersetSecretKey: ''

  init:
    createAdmin: false

  postgresql:
    enabled: false

  redis:
    enabled: false

  supersetNode:
    connections:
      redis_host: '{{ .Release.Name }}-superset-redis-headless'
      db_host: '{{ .Release.Name }}-superset-postgresql'

  bootstrapScript: |
    #!/bin/bash
    pip install authlib==1.3.0

  configOverrides:
    enable_oauth: |
      SECRET_KEY = '{{ tpl .Values.supersetSecretKey $ }}' or 'OPENG2P_SUPER_SECRET_KEY'

      # This will make sure the redirect_uri is properly computed, even with SSL offloading
      ENABLE_PROXY_FIX = True

      from flask_appbuilder.security.manager import AUTH_OAUTH
      AUTH_TYPE = AUTH_OAUTH
      OAUTH_PROVIDERS = [
        {
          "name": "keycloak",
          "icon": "fa-key",
          "token_key": "access_token",
          "remote_app": {
            "client_id": "{{ tpl .Values.oidcClientId $ }}",
            "client_secret": "{{ tpl .Values.oidcClientSecret $ }}",
            "api_base_url": "{{ tpl .Values.oidcIssuerUrl $ }}/protocol/openid-connect",
            "client_kwargs": {"scope": "email profile openid"},
            "access_token_url": "{{ tpl .Values.oidcIssuerUrl $ }}/protocol/openid-connect/token",
            "jwks_uri": "{{ tpl .Values.oidcIssuerUrl $ }}/protocol/openid-connect/certs",
            "authorize_url": "{{ tpl .Values.oidcIssuerUrl $ }}/protocol/openid-connect/auth",
            "request_token_url": None
          },
        }
      ]

      # Map Authlib roles to superset roles
      AUTH_ROLES_MAPPING = {
        "Public": ["Public"],
        "Admin": ["Admin"],
      }

      AUTH_ROLES_SYNC_AT_LOGIN = True

      # Will allow user self registration, allowing to create Flask users from Authorized User
      AUTH_USER_REGISTRATION = True

      # The default user self registration role
      # AUTH_USER_REGISTRATION_ROLE = "Public"

      from superset.security import SupersetSecurityManager
      class CustomSsoSecurityManager(SupersetSecurityManager):
        def oauth_user_info(self, provider, response=None):
          if provider == "keycloak":
            me = self.appbuilder.sm.oauth_remotes[provider].get(
              "openid-connect/userinfo"
            )
            me.raise_for_status()
            data = me.json()
            return {
              "username": data.get("preferred_username", ""),
              "first_name": data.get("given_name", ""),
              "last_name": data.get("family_name", ""),
              "email": data.get("email", ""),
              "role_keys": data.get("client_roles", []),
            }
          return {}

      CUSTOM_SECURITY_MANAGER = CustomSsoSecurityManager

  istio:
    enabled: true
    virtualservice:
      enabled: true
      host: ""
      gateway: "internal"
      destination: '{{ .Release.Name }}-superset'
      destinationPort: "8088"
    gateway:
      enabled: false
      host: ""
      ingressController:
        istio: ingressgateway
      httpTlsRedirect: true
      httpEnabled: true
      httpsEnabled: false
      tls:
        mode: SIMPLE
        credentialName: ""

loggingFlow:
  enabled: false
  outputRef: '{{ tpl .Values.global.socialRegistryOpensearchInstallationName $ }}'
  extraLocalOutputRefs: []
  globalOutputRefs: []
  parser:
    key_name: message
    parse:
      type: regexp
      expression: /^(?<asctime>(\S+)(\s)(\S+))\s+(?<pid>\S+)\s+(?<levelname>\S+)\s+(?<dbname>\S+)\s+(?<name>\S+)\s+(?<message>.*)$/
    remove_key_name_field: true
    replace_invalid_sequence: true
    reserve_data: true
  extraFilters: []

istio:
  enabled: true
  virtualservice:
    enabled: true
    host: ""
    gateway: "internal"
    destination: '{{ .Release.Name }}-odoo'
    destinationPort: '{{ .Values.odoo.service.port }}'
    prefix: /
    rewriteUri: ""
  gateway:
    enabled: false
    host: ""
    ingressController:
      istio: ingressgateway
    httpTlsRedirect: true
    httpEnabled: true
    httpsEnabled: false
    tls:
      mode: SIMPLE
      credentialName: ""
