global:
  keycloakBaseUrl: https://keycloak.openg2p.org
  keycloakIssuerUrl: '{{ tpl .Values.global.keycloakBaseUrl $ }}/realms/master'

  postgresqlHost: openg2p-commons-postgresql 
  postgresqlPort: 5432
  opensearchInstallationName: openg2p-commons-opensearch
  reportingInstallationName: openg2p-commons-reporting

  srAdminHostname: registry.devops.openg2p.org
  srOdkCentralHostname: odk.devops.openg2p.org
  srMinioHostname: minio.devops.openg2p.org
  srOpensearchHostname: opensearch.devops.openg2p.org
  srKafkaUiHostname: kafka.devops.openg2p.org
  srSupersetHostname: superset.devops.openg2p.org
  srLandingPageHostname: registry.devops.openg2p.org

  mailInstallationName: openg2p-commons-mail

  srOdooOidcClientId: 'openg2p-sr-{{ .Release.Namespace }}'
  srOdooOidcClientSecret: ''

  minioInstallationName: openg2p-commons-minio 

  sysAdminEmail: admin@openg2p.sandbox.net

  keymanagerInstallationName: openg2p-commons-keymanager
  srKeymanagerAuthEnabled: false
  srKeymanagerAppId: OPENG2P_SR

postgres-init:
  enabled: true
  postgresql:
    host: '{{ .Values.global.postgresqlHost }}'
    port: 5432
    # Hard coding. Same as one defined under Odoo
    existingSecret: openg2p-commons-postgresql
    existingSecretPostgresPasswordKey: postgres-password
  database:
    # Same as db in Odoo - make sure any changes to the name are synced with Odoo definitions
    name: '{{ .Release.Name }}_{{ .Release.Namespace }}_db'
    user: '{{ .Release.Name}}_{{ .Release.Namespace }}_db_user'
    # Same secret as Postgresql - the Odoo chart expects all keys in the same secret, hence we are forced to this
    secret: openg2p-commons-postgresql
    # As convention same as user 
    secretUserPasswordKey: '{{ .Release.Name}}_{{ .Release.Namespace }}_db_user'

odoo:
  enabled: true

  hostname: '{{ tpl .Values.global.srAdminHostname $ }}'

  oidcIssuerUrl: '{{ tpl .Values.global.keycloakIssuerUrl $ }}'
  oidcClientId: '{{ tpl .Values.global.srOdooOidcClientId $ }}'
  oidcClientSecret: '{{ tpl .Values.global.srOdooOidcClientSecret $ }}'

  mailInstallationName: '{{ tpl .Values.global.mailInstallationName $ }}'
  keymanagerInstallationName: '{{ tpl .Values.global.keymanagerInstallationName $ }}'
  minioInstallationName: '{{ tpl .Values.global.minioInstallationName $ }}' 

  extraAddonsUrlsToPull: ''

  image:
    repository: openg2p/openg2p-registry-core
    tag: develop
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 80

  # TODO: Remove this and use global.sysAdminEmail
  odooEmail: admin@openg2p.org
  odooDatabaseFilter: ""

  withoutDemo: all

  loadDemoData: false  # This is redundant. Has no effect on inside the docker. Use withoutDemo instead.

  diagnosticMode:
    enabled: false  # Do not change this.

  livenessProbe:
    enabled: false

  containerSecurityContext:
    enabled: false

  podSecurityContext:
    enabled: false

  # We are using external database, hence default postgres is disabled
  postgresql:
    enabled: false

  externalDatabase:
    create: true
    # Global postgresqlHost assigned in _helpers.tpl directly (otherwise it is not possible to pass to Odoo char)
    host: ''
    port: 5432
    # Directly defined in _helpers.tpl: {{- printf "%s%sdb" .Release.Name .Release.Namespace -}}
    database: ''
    # Directly defined in _helpers.tpl: printf "%s-%s-user" .Release.Name .Release.Namespace
    user: ''
    # Provided via secrets below
    password: ""
    postgresqlPostgresUser: "postgres"
    # Passed via secrets
    postgresqlPostgresPassword: ""
    # The secrets below should be created before this installation is done. All keys within same secret. 
    existingSecret: openg2p-commons-postgresql
    # Directly defined in _helpers.tpl: printf "%s-%s-user" .Release.Name .Release.Namespace
    existingSecretPasswordKey: ''
    existingSecretPostgresPasswordKey: postgres-password

  extraEnvVars: '{{- include "socialRegistry.baseEnvVars" (dict "envVars" (merge (deepCopy .Values.envVars) (deepCopy .Values.envVarsFrom)) "context" $) }}'

  envVars:
    #ODOO_DATABASE_FILTER_OVERRIDE: "^registry_devops_db$"
    ODOO_SKIP_MODULES_UPDATE: yes
    LIMIT_TIME_REAL: 5000
    # This disables Odoo showing selection of databases if there are multiple databases (in our case we have only one DB for this deployment
    LIST_DB: False
    SERVER_WIDE_MODULES: base,web,queue_job

    # not using bitnami smtpHost and smtpPort variables, because of lack of templating
    OPENG2P_SMTP_HOST: '{{ tpl .Values.global.mailInstallationName $ }}'
    OPENG2P_SMTP_PORT: 25

    LOG_HANDLER: "'':INFO''"
    LOG_DB: False  # Do NOT use this. Use LOG_HANDLER instead.

    ODOO_BOOTSTRAP_MODULES: >-
      base,
      g2p_app_filter,
      g2p_auth_oidc,
      g2p_auth_oidc_keycloak,
      g2p_registry

    EXTRA_ADDONS_URLS_TO_PULL: '{{ tpl .Values.extraAddonsUrlsToPull $ }}'

    eEYMANAGER_API_BASE_URL: 'http://{{ tpl .Values.global.keymanagerInstallationName $ }}/v1/keymanager'
    KEYMANAGER_AUTH_ENABLED: '{{ .Values.global.srKeymanagerAuthEnabled }}'
    KEYMANAGER_AUTH_URL: '{{ tpl .Values.oidcIssuerUrl $ }}/protocol/openid-connect/token'
    KEYMANAGER_AUTH_CLIENT_ID: '{{ tpl .Values.oidcClientId $ }}'
    KEYMANAGER_AUTH_CLIENT_SECRET: '{{ tpl .Values.oidcClientSecret $ }}'
    KEYMANAGER_ENCRYPT_APP_ID: '{{ tpl .Values.global.srKeymanagerAppId $ }}'
    KEYMANAGER_ENCRYPT_REF_ID: "ENCRYPT"
    KEYMANAGER_SIGN_APP_ID: '{{ tpl .Values.global.srKeymanagerAppId $ }}'
    KEYMANAGER_SIGN_REF_ID: ""

    KEYCLOAK_ISSUER_URL: '{{ tpl .Values.oidcIssuerUrl $ }}'
    KEYCLOAK_CLIENT_ID: '{{ tpl .Values.oidcClientId $ }}'
    KEYCLOAK_CLIENT_SECRET: '{{ tpl .Values.oidcClientSecret $ }}'

    S3_URL: 'http://{{ tpl .Values.global.minioInstallationName $ }}:9000'
    # S3_REGION: "other"  # For minio
    WAIT_FOR_POSTGRES: 180

  envVarsFrom:
    S3_ACCESS_KEY_ID:
      secretKeyRef:
        key: root-user
        name: '{{ tpl .Values.global.minioInstallationName $ }}'
    S3_SECRET_ACCESS_KEY:
      secretKeyRef:
        key: root-password
        name: '{{ tpl .Values.global.minioInstallationName $ }}'

  istio:
    enabled: true
    virtualservice:
      enabled: true
      host: ""
      gateway: "internal"
      destination: '{{ include "common.names.fullname" . }}'
      destinationPort: '{{ .Values.service.port }}'
      prefix: /
      rewriteUri: ""
    gateway:
      enabled: false
      host: ""
      ingressController:
        istio: ingressgateway
      httpTlsRedirect: true
      httpEnabled: true
      httpsEnabled: false
      tls:
        mode: SIMPLE
        credentialName: ""

reporting-init:
  enabled: true
  reportingInstallationName: '{{ tpl .Values.global.reportingInstallationName $ }}'
  opensearchInstallationName: '{{ tpl .Values.global.opensearchInstallationName $ }}'
  postgresqlInstallationName: '{{ tpl .Values.global.postgresqlHost $ }}' 
  gitConfig:
    enabled: true
    repoUrl: https://github.com/openg2p/openg2p-reporting
    branch: develop
    subDir: "scripts/social-registry"
  envVars:
    # Same as odoo.externalDatabase.database
    DB_NAME: '{{ tpl (printf "%s%sdb" .Release.Name .Release.Namespace) $ }}' 
  hookAnnotations:
    "helm.sh/hook-weight": "0"

loggingFlow:
  enabled: false
  opensearchInstallationName: '{{ tpl .Values.global.opensearchInstallationName $ }}'
  outputRef: '{{ tpl .Values.loggingFlow.opensearchInstallationName $ }}'
  extraLocalOutputRefs: []
  globalOutputRefs: []
  parser:
    key_name: message
    parse:
      type: regexp
      expression: /^(?<asctime>(\S+)(\s)(\S+))\s+(?<pid>\S+)\s+(?<levelname>\S+)\s+(?<dbname>\S+)\s+(?<name>\S+)\s+(?<message>.*)$/
    remove_key_name_field: true
    replace_invalid_sequence: true
    reserve_data: true
  extraFilters: []

idgenerator:
  enabled: false
  hostname: '{{ tpl .Values.global.srAdminHostname $ }}'
  springCloudConfig:
    enabled: true
    profile: default
    gitRepo:
      url: https://github.com/openg2p/mosip-config
      branch: master
  envVars:
    auth_server_admin_allowed_audience: 'openg2p-sr,openg2p-sr-{{ .Release.Namespace }}'
  envVarsFrom:
    db_dbuser_password:
      secretKeyRef:
        name: '{{ tpl .Values.global.postgresqlHost $ }}-addl-user-passwords'
        key: kerneluser

mosipKernelPostgresInit:
  enabled: false
  image:
    repository: mosipid/postgres-init
    tag: 1.2.0.1-B4
    pullPolicy: Always
  containerSecurityContext:
    enabled: false
  podSecurityContext:
    enabled: false
  commonAnnotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
  command:
    - bash
  args:
    - -c
    - until pg_isready -h ${DB_SERVERIP} -p ${DB_PORT}; do sleep 3; done && ./postgres-init.sh

  envVars:
    MOSIP_DB_NAME: mosip_kernel
    DB_SERVERIP: '{{ tpl .Values.global.postgresqlHost $ }}'
    DB_PORT: '5432'
    SU_USER: postgres
    DB_USER: kerneluser
    DML_FLAG: '0'
    GIT_REPO_URL: https://github.com/mosip/commons.git
    GIT_BRANCH: v1.2.0.1
  envVarsFrom:
    SU_USER_PWD:
      secretKeyRef:
        name: '{{ tpl .Values.global.postgresqlHost $ }}'
        key: postgres-password
    DBUSER_PWD:
      secretKeyRef:
        name: '{{ tpl .Values.global.postgresqlHost $ }}-addl-user-passwords'
        key: kerneluser

redis:
  #nameOverride: '{{ .Release.Name }}-redis'
  enabled: false
  architecture: standalone
  auth:
    enabled: false
  master:
    resourcesPreset: none
    persistence:
      enabled: false

openg2p-registry-bg-tasks:
  enabled: false
  nameOverride: bg-tasks

  redisInstallationName: '{{ .Release.Name }}-redis'

  producer:
    enabled: true
  worker:
    enabled: true
    envVars:
      REGISTRY_CELERY_WORKERS_AUTH_CLIENT_ID: '{{ tpl .Values.global.srOdooOidcClientId $ }}'
      REGISTRY_CELERY_WORKERS_AUTH_CLIENT_SECRET: '{{ tpl .Values.global.srOdooOidcClientSecret $ }}'

landing:
  enabled: false
  hostname: '{{ tpl .Values.global.srLandingPageHostname $ }}'

  commonLabels:
    app.kubernetes.io/name: '{{ include "common.names.name" . }}-landing'
  commonAnnotations: {}
  podLabels:
    app.kubernetes.io/name: '{{ include "common.names.name" . }}-landing'
  podAnnotations: {}

  replicaCount: 1

  service:
    type: ClusterIP
    port: 80
    nodePorts:
      http: ""
      https: ""
    externalTrafficPolicy: Cluster

  image:
    repository: openg2p/openg2p-social-registry-landing
    tag: "develop"
    pullPolicy: Always
    pullSecrets: []

  containerPort: 80

  startupProbe:
    enabled: true
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 30
    successThreshold: 1

  livenessProbe:
    enabled: true
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 20
    periodSeconds: 30
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1

  readinessProbe:
    enabled: true
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1

  command: []
  args: []

  hostAliases: []

  resources: {}

  containerSecurityContext:
    enabled: false
    runAsUser: 1001
    runAsNonRoot: true

  podSecurityContext:
    enabled: false
    fsGroup: 1001

  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []
  affinity: {}
  nodeSelector: {}
  tolerations: []

  priorityClassName: ""
  lifecycleHooks: {}

  updateStrategy:
    type: RollingUpdate

  initContainers: []
  sidecars: []

  extraVolumes: []
  extraVolumeMounts: []

  envVars:
    SR_ADMIN_URL: 'https://{{ tpl .Values.global.srAdminHostname $ }}/web'
    SR_REPORTING_URL: 'https://{{ tpl .Values.global.srOpensearchHostname $ }}'
    SR_LOGGING_URL: 'https://{{ tpl .Values.global.srOpensearchHostname $ }}'
    SR_MINIO_URL: 'https://{{ tpl .Values.global.srMinioHostname $ }}'
    SR_ODK_URL: 'https://{{ tpl .Values.global.srOdkCentralHostname $ }}'
    SR_KAFKA_URL: 'https://{{ tpl .Values.global.srKafkaUiHostname $ }}'
    SR_SUPERSET_URL: 'https://{{ tpl .Values.global.srSupersetHostname $ }}'
    SR_KEYCLOAK_ACCOUNT_CONSOLE_URL: '{{ tpl .Values.global.keycloakIssuerUrl $ }}/account'
    SR_VERSION: '{{ .Chart.Version }}'
    SR_APP_VERSION: '{{ .Values.odoo.image.tag }}'

  envVarsFrom: {}

  istio:
    enabled: true
    virtualservice:
      enabled: true
      host: ""
      gateway: "internal"
      destination: '{{ include "common.names.fullname" . }}-landing'
      destinationPort: '{{ .Values.landing.service.port }}'
      prefix: /
      rewriteUri: ""
    gateway:
      enabled: false
      host: ""
      ingressController:
        istio: ingressgateway
      httpTlsRedirect: true
      httpEnabled: true
      httpsEnabled: false
      tls:
        mode: SIMPLE
        credentialName: ""
